apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cks-terminal-mgmt
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    external-dns.alpha.kubernetes.io/hostname: "endpoint"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "endpoint"
      secretName: cks-terminal-mgmt-tls
  rules:
    - host: "endpoint"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cks-terminal-mgmt
                port:
                  number: 8080
