apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.fullstack.pw/library/cks-terminal-mgmt
    newTag: latest

configMapGenerator:
  - name: cks-terminal-mgmt-config
    behavior: merge
    envs:
      - configmap
