apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.fullstack.pw/library/cks-terminal-mgmt
    newTag: 4812b36a6501a64bd161e77d7cf56570a6d6f777

configMapGenerator:
  - name: cks-terminal-mgmt-config
    behavior: merge
    envs:
      - configmap
